---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: cp-example-instance-1
  labels:
    testing.upbound.io/example-name: cp-example-instance-1
spec:
  providerConfigRef:
    name: aws-upbound-pc
  forProvider:
    region: us-west-1
    ami: ami-07b068f843ec78e72
    instanceType: t2.medium
    associatePublicIpAddress: true
    availabilityZone: cp-example-public-us-east-1b
    disableApiStop: true
    monitoring: true
    tags:
      Name: cp-example-instance-1
    volumeTags:
      Name: cp-example-instance-1