---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: cp-example-instance-1-sg
  # annotations:
  #   crossplane.io/external-name: sg-0e880dcde534bafc1 # manage existing SecurityGroup
  labels:
    name: cp-example-instance-1-sg
spec:
  providerConfigRef:
    name: aws-upbound-pc
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: cp-example-instance-1-sg
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    description: Security group for EC2 instance
    name: cp-example-instance-1-sg
    region: us-east-1
    tags:
      Name: cp-example-instance-1-sg
    vpcIdRef: 
      name: cp-example-vpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupEgressRule
metadata:
  name: cp-example-instance-1-sg-egress
  # annotations:
  #   crossplane.io/external-name: sg-0e880dcde534bafc1 # manage existing SecurityGroup
  labels:
    name: cp-example-instance-1-sg-egress
spec:
  providerConfigRef:
    name: aws-upbound-pc
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: cp-example-instance-1-sg-egress
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    description: "Allow all egress traffic"
    region: us-west-1
    cidrIpv4: 0.0.0.0/0
    fromPort: 0
    toPort: 0
    ipProtocol: -1
    securityGroupIdSelector:
      matchLabels:
        name: cp-example-instance-1-sg
    tags:
      Name: cp-example-instance-1-sg-egress
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupIngressRule
metadata:
  name: cp-example-instance-1-sg-ingress-22
  # annotations:
  #   crossplane.io/external-name: sg-0e880dcde534bafc1 # manage existing SecurityGroup
  labels:
    name: cp-example-instance-1-sg-ingress-22
spec:
  forProvider:
    description: "Allow all ingress traffic for port 22"
    region: us-west-1
    cidrIpv4: 0.0.0.0/0
    fromPort: 22
    toPort: 22
    ipProtocol: tcp
    securityGroupIdSelector:
      matchLabels:
        name: cp-example-instance-1-sg
    tags:
      Name: cp-example-instance-1-sg-ingress-22
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupIngressRule
metadata:
  name: cp-example-instance-1-sg-ingress-22
  # annotations:
  #   crossplane.io/external-name: sg-0e880dcde534bafc1 # manage existing SecurityGroup
  labels:
    name: cp-example-instance-1-sg-ingress-80
spec:
  forProvider:
    description: "Allow all ingress traffic for port 80"
    region: us-west-1
    cidrIpv4: 0.0.0.0/0
    fromPort: 80
    toPort: 80
    ipProtocol: tcp
    securityGroupIdSelector:
      matchLabels:
        name: cp-example-instance-1-sg
    tags:
      Name: cp-example-instance-1-sg-ingress-80
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: EBSVolume
metadata:
  name: cp-example-instance-1-ebs
  # annotations:
  #   crossplane.io/external-name: ebs-06b5984e75c31ff46 # manage existing Volume
  labels:
    name: cp-example-instance-1-ebs
spec:
  providerConfigRef:
    name: aws-upbound-pc
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: cp-example-instance-1-ebs
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    region: us-west-1
    availabilityZone: us-east-1a
    size: 20
    type: gp2
    tags:
      - key: Name
        value: cp-example-instance-1-ebs
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: cp-example-instance-1
  # annotations:
  #   crossplane.io/external-name: ec2-06b5984e75c31ff46 # manage existing EC2
  labels:
    testing.upbound.io/example-name: cp-example-instance-1
    name: cp-example-instance-1-ebs
spec:
  providerConfigRef:
    name: aws-upbound-pc
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: cp-example-instance-1
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    region: us-east-1
    ami: ami-05576a079321f21f8
    instanceType: t2.medium
    associatePublicIpAddress: true
    availabilityZone: us-east-1a
    disableApiStop: false
    monitoring: true
    securityGroupIdRefs:
      - name: cp-example-instance-1-sg
    subnetIdSelector:
      matchControllerRef: true
    blockDeviceMappings:
      - deviceName: /dev/xvdb
        ebs:
          volumeIdRef:
            name: cp-example-instance-1-ebs
    tags:
      Name: cp-example-instance-1
    volumeTags:
      Name: cp-example-instance-1
    userData: |
      #!/bin/bash
      mkdir -p /mount/ebs1
      mkfs.ext4 /dev/xvdb
      mount /dev/xvdb /mount/ebs1
      echo '/dev/xvdb /mount/ebs1 ext4 defaults 0 0' >> /etc/fstab