---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: cp-example-instance-1-sg
spec:
  providerConfigRef:
    name: aws-upbound-pc
  forProvider:
    description: Security group for EC2 instance
    groupName: cp-example-instance-1-sg
    region: us-east-1
    vpcIdRef: 
      name: cp-example-vpc
    tags:
      Name: cp-example-instance-1-sg
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: cp-example-instance-1
  labels:
    testing.upbound.io/example-name: cp-example-instance-1
spec:
  providerConfigRef:
    name: aws-upbound-pc
  forProvider:
    region: us-east-1
    ami: ami-05576a079321f21f8
    instanceType: t2.medium
    associatePublicIpAddress: true
    availabilityZone: cp-example-public-us-east-1b
    disableApiStop: true
    monitoring: true
    securityGroupIds:
      - cp-example-instance-1-sg
    subnetIdSelector:
      matchLabels:
        name: cp-example-public-us-east-1a
    tags:
      Name: cp-example-instance-1
    volumeTags:
      Name: cp-example-instance-1