---
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: cp-example-bucket
spec:
  providerConfigRef:
    name: aws-upbound-pc
  forProvider:
    region: us-east-1
    tags:
      Name: cp-example-bucket