---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: cp-example-vpc
  # annotations:
  #   crossplane.io/external-name: vpc-06b5984e75c31ff46 # manage existing VPC
  labels:
    name: cp-example-vpc
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    region: us-east-1
    cidrBlock: 10.100.0.0/16
    enableDnsSupport: true
    enableDnsHostnames: true
    instanceTenancy: default
    enableNetworkAddressUsageMetrics: true
    tags:
      ManagedBy: Crossplane
      Name: cp-example-vpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: EIP
metadata:
  name: cp-example-eip
  # annotations:
  #   crossplane.io/external-name: eipalloc-088d9b4c5bf8cc067 # manage existing EIP
  labels:
    name: cp-example-eip
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    region: us-east-1
    vpc: true
    tags:
      Name: cp-example-eip
      ManagedBy: crossplane
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: NATGateway
metadata:
  name: cp-example-nat
  # annotations:
  #   crossplane.io/external-name: nat-02bb3805fb0408de2 # manage existing NAT
  labels:
    name: cp-example-nat
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    connectivityType: public
    region: us-east-1
    allocationIdRef:
      name: cp-example-eip
    subnetIdSelector:
      matchLabels:
        name: cp-example-public-us-east-1a-subnet
    tags:
      Name: cp-example-nat
      ManagedBy: crossplane
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: cp-example-igw
  # annotations:
  #   crossplane.io/external-name: igw-0c36920ef01a2c06b # manage existing IGW
  labels:
    name: cp-example-igw
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    region: us-east-1
    tags:
      Name: cp-example-igw
      ManagedBy: Crossplane
    vpcIdRef:
      name: cp-example-vpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: cp-example-private-us-east-1a-subnet
  # annotations:
  #   crossplane.io/external-name: subnet-08fabd0299c17c277 # manage existing Subnet
  labels:
    name: cp-example-private-us-east-1a-subnet
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    availabilityZone: us-east-1a
    cidrBlock: 10.100.1.0/24
    region: us-east-1
    tags:
      Name: cp-example-private-us-east-1a-subnet
      ManagedBy: Crossplane
    vpcIdRef:
      name: cp-example-vpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: cp-example-private-us-east-1b-subnet
  # annotations:
  #   crossplane.io/external-name: subnet-03c18525e77fda56b # manage existing Subnet
  labels:
    name: cp-example-private-us-east-1b-subnet
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    availabilityZone: us-east-1b
    cidrBlock: 10.100.2.0/24
    region: us-east-1
    tags:
      Name: cp-example-private-us-east-1b-subnet
      ManagedBy: Crossplane
    vpcIdRef:
      name: cp-example-vpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: cp-example-public-us-east-1a-subnet
  # annotations:
  #   crossplane.io/external-name: subnet-0d4def7ee346b5654 # manage existing Subnet
  labels:
    name: cp-example-public-us-east-1a-subnet
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    availabilityZone: us-east-1a
    cidrBlock: 10.100.3.0/24
    region: us-east-1
    tags:
      Name: cp-example-public-us-east-1a-subnet
      ManagedBy: Crossplane 
    vpcIdRef:
      name: cp-example-vpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: cp-example-public-us-east-1b-subnet
  # annotations:
  #   crossplane.io/external-name: subnet-0cef0db5956f355f0 # manage existing Subnet
  labels:
    name: cp-example-public-us-east-1b-subnet
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    availabilityZone: us-east-1b
    cidrBlock: 10.100.4.0/24
    region: us-east-1
    tags:
      Name: cp-example-public-us-east-1b-subnet
      ManagedBy: Crossplane 
    vpcIdRef:
      name: cp-example-vpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: cp-example-private-rtb
  # annotations:
  #   crossplane.io/external-name: rtb-0289b5ea251088cb6 # manage existing RouteTable
  labels:
    name: cp-example-private-rtb
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    region: us-east-1
    tags:
      Name: cp-example-private-rtb
      ManagedBy: crossplane
    vpcIdRef:
      name: cp-example-vpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Route
metadata:
  name: cp-example-private-rt
  labels:
    name: cp-example-private-rtb
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    natGatewayIdRef:
      name: cp-example-nat
    region: us-east-1
    routeTableIdRef:
      name: cp-example-private-rtb
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: cp-example-public-rtb
  # annotations:
  #   crossplane.io/external-name: rtb-00ec3f3036a7ab799 # manage existing RouteTable
  labels:
    name: cp-example-public-rtb
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    region: us-east-1
    tags:
      Name: cp-example-public-rtb
      ManagedBy: crossplane
    vpcIdRef:
      name: cp-example-vpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Route
metadata:
  name: cp-example-public-rt
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    gatewayIdRef:
      name: cp-example-igw
    region: us-east-1
    routeTableIdRef:
      name: cp-example-public-rtb
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: cp-example-private-us-east-1a-rta
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    region: us-east-1
    routeTableIdRef:
      name: cp-example-private-rtb
    subnetIdRef:
      name: cp-example-private-us-east-1a-subnet
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: cp-example-private-us-east-1b-rta
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    region: us-east-1
    routeTableIdRef:
      name: cp-example-private-rtb
    subnetIdRef:
      name: cp-example-private-us-east-1b-subnet
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: cp-example-public-us-east-1a-rta
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    region: us-east-1
    routeTableIdRef:
      name: cp-example-public-rtb
    subnetIdRef:
      name: cp-example-public-us-east-1a-subnet
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: cp-example-public-us-east-1b-rta
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    region: us-east-1
    routeTableIdRef:
      name: cp-example-public-rtb
    subnetIdRef:
      name: cp-example-public-us-east-1b-subnet
