---
apiVersion: iam.aws.upbound.io/v1beta1
kind: InstanceProfile
metadata:
  name: ssm-agent-instanceprofile
  # annotations:
  #   crossplane.io/external-name: sg-0e880dcde534bafc1 # manage existing SecurityGroup
  labels:
    name: ssm-agent-instanceprofile
    ManagedBy: crossplane
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    roleSelector:
      matchLabels:
        name: ssm-agent-role
    tags:
      Name: ssm-agent-instanceprofile
      ManagedBy: crossplane
