crds:
  install: true
  keep: true
global:
  logging:
    format: text
    level: info
configs:
  cm:
    create: true
    exec.enabled: true
    timeout.reconciliation: 120s
    controller.sync.timeout.seconds: 300
    server.insecure: true
    admin.enabled: true
    statusbadge.enabled: true
  params:
    server.insecure: true
dex:
  enabled: false

