---
bases:
  - ../helmfile/defaults.yaml
  - ../helmfile/environments.yaml
  - ../helmfile/repositories.yaml
  # - ../helmfile/templates.yaml
---
templates:
  default: &default
    labels:
      managedBy: Helmfile
    namespace: nginx
    missingFileHandler: Error
    values:
      - ../../envs/{{ env "ARGOCD_ENV_ENVIRONMENT" }}/{{ env "ARGOCD_ENV_APP_NAME" }}/values.yaml
      - values/nginx.yaml.gotmpl

releases:
  - name: nginx
    chart: bitnami/nginx
    version: '19.0.3'
    secrets: []
    <<: *default
