repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: nginx
    namespace: nginx
    chart: bitnami/nginx
    version: '19.0.3'
    values:
      - values/nginx.yaml
      - values/nginx.yaml.gotmpl
      - ../../envs/{{ env "ARGOCD_ENV_ENVIRONMENT" }}/{{ env "ARGOCD_ENV_APP_NAME" }}/values.yaml
