---
bases:
  - ../helmfile/defaults.yaml
  - ../helmfile/environments.yaml
  - ../helmfile/repositories.yaml
---
{{ readFile "../helmfile/templates.yaml" }}

releases:
  - name: nginx
    chart: bitnami/nginx
    version: '19.0.3'
    namespace: nginx
    secrets: []
    <<: *default
