---
bases:
  - ../helmfile/defaults.yaml
  - ../helmfile/environments.yaml
  - ../helmfile/repositories.yaml
---
{{ readFile "../helmfile/templates.yaml" }}

releases:
  - name: nginx
    chart: bitnami-aks/nginx
    version: '19.0.3'
    namespace: nginx
    values:
      - values/values.yaml.gotmpl
      - ../../envs/{{`{{ requiredEnv "ARGOCD_ENV_ENVIRONMENT" }}`}}/{{`{{ requiredEnv "ARGOCD_ENV_APP_NAME" }}`}}/values.yaml
    secrets:
      - values/values-secret.yaml
      - ../../envs/{{`{{ requiredEnv "ARGOCD_ENV_ENVIRONMENT" }}`}}/{{`{{ requiredEnv "ARGOCD_ENV_APP_NAME" }}`}}/values-secret.yaml
    <<: *default
