---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupEgressRule
metadata:
  name: ec2-1-sg-egress
  # annotations:
  #   crossplane.io/external-name: sg-0e880dcde534bafc1 # manage existing SecurityGroup
  labels:
    name: ec2-1-sg-egress
    ManagedBy: crossplane
    argocd.argoproj.io/instance: ec2-1
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    description: "Allow all egress traffic"
    region: us-east-1
    cidrIpv4: 0.0.0.0/0
    ipProtocol: "-1"
    securityGroupIdRef:
      name: ec2-1-sg
    tags:
      Name: ec2-1-sg-egress
      ManagedBy: crossplane
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupIngressRule
metadata:
  name: ec2-1-sg-ingress-22
  # annotations:
  #   crossplane.io/external-name: sg-0e880dcde534bafc1 # manage existing SecurityGroup
  labels:
    name: ec2-1-sg-ingress-22
    ManagedBy: crossplane
    argocd.argoproj.io/instance: ec2-1
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    description: "Allow all ingress traffic for port 22"
    region: us-east-1
    cidrIpv4: 0.0.0.0/0
    fromPort: 22
    toPort: 22
    ipProtocol: tcp
    securityGroupIdRef:
      name: ec2-1-sg
    tags:
      Name: ec2-1-sg-ingress-22
      ManagedBy: crossplane
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupIngressRule
metadata:
  name: ec2-1-sg-ingress-80
  # annotations:
  #   crossplane.io/external-name: sg-0e880dcde534bafc1 # manage existing SecurityGroup
  labels:
    name: ec2-1-sg-ingress-80
    ManagedBy: crossplane
    argocd.argoproj.io/instance: ec2-1
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    description: "Allow all ingress traffic for port 80"
    region: us-east-1
    cidrIpv4: 0.0.0.0/0
    fromPort: 80
    toPort: 80
    ipProtocol: tcp
    securityGroupIdRef:
      name: ec2-1-sg
    tags:
      Name: ec2-1-sg-ingress-80
      ManagedBy: crossplane
