---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: cp-example-eks-cluster-role
  # annotations:
  #   crossplane.io/external-name: sg-0e880dcde534bafc1 # manage existing SecurityGroup
  labels:
    name: cp-example-role-with-policy
    ManagedBy: crossplane
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    description: "Role for SSM agent"
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "ec2:CreateTags"
            ],
            "Resource": "arn:aws:ec2:*:*:instance/*",
            "Condition": {
              "ForAnyValue:StringLike": {
                "aws:TagKeys": "kubernetes.io/cluster/*"
              }
            }
          },
          {
            "Effect": "Allow",
            "Action": [
              "ec2:DescribeInstances",
              "ec2:DescribeNetworkInterfaces",
              "ec2:DescribeVpcs",
              "ec2:DescribeDhcpOptions",
              "ec2:DescribeAvailabilityZones",
              "ec2:DescribeInstanceTopology",
              "kms:DescribeKey"
            ],
            "Resource": "*"
          }
        ]
      }
    tags:
      Name: cp-example-eks-cluster-role
      ManagedBy: crossplane
