---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: cp-example-eks-cluster-role
  # annotations:
  #   crossplane.io/external-name: sg-0e880dcde534bafc1 # manage existing SecurityGroup
  labels:
    name: cp-example-role-with-policy
    ManagedBy: crossplane
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    description: "Role for SSM agent"
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    tags:
      Name: cp-example-eks-cluster-role
      ManagedBy: crossplane
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: cp-example-eks-cluster-role-policy-attach
  # annotations:
  #   crossplane.io/external-name: sg-0e880dcde534bafc1 # manage existing SecurityGroup
  labels:
    name: cp-example-eks-cluster-role-policy-attach
    ManagedBy: crossplane
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    policyArnRef:
      - name: AmazonEKSBlockStoragePolicy
      - name: AmazonEKSClusterPolicy
      - name: AmazonEKSComputePolicy
      - name: AmazonEKSLoadBalancingPolicy
      - name: AmazonEKSNetworkingPolicy
      - name: AmazonEC2ContainerRegistryPullOnly
      - name: AmazonEKSWorkerNodeMinimalPolicy
    roleName: cp-example-eks-cluster-role