common_params:
  - environment: dev
    domain: 'dev.example.com'
    project: 'dev'
    git_revision: main
helm_apps:
  - name: 'argocd'
    namespace: 'argocd'
    project: 'default'
    repoUrl: 'https://argoproj.github.io/argo-helm'
    chart: 'argo-cd'
    targetRevision: '>=7.8.0 <7.9.0'
    automatedPrune: 'false'
  - name: 'metrics-server'
    namespace: 'metrics-server'
    repoUrl: 'https://kubernetes-sigs.github.io/metrics-server/'
    chart: metrics-server
    targetRevision: '>=3.12.0 <3.13.0'
    prune: true
  - name: 'kubernetes-dashboard'
    namespace: 'kubernetes-dashboard'
    repoUrl: 'https://kubernetes.github.io/dashboard'
    chart: 'kubernetes-dashboard'
    targetRevision: '>=7.10.0 <7.11.0'
  - name: 'crossplane'
    namespace: 'crossplane-system'
    repoUrl: 'https://charts.crossplane.io/stable'
    chart: 'crossplane'
    targetRevision: '>=1.19.0 <1.20.0'
    automatedPrune: 'false'
helmfile_apps:
  - name: nginx
    namespace: "nginx"
    project: "dev"
    environment: dev
k8s_manifest_apps:
  # - name: "aws-s3"
  #   namespace: 'crossplane-system'
  #   config_dir: "aws-s3"
  # - name: "aws-vpc"
  #   namespace: 'crossplane-system'
  #   config_dir: "aws-vpc"
  # - name: "aws-ec2"
  #   namespace: 'crossplane-system'
  #   config_dir: "aws-ec2"
  # - name: "aws-ssm"
  #   namespace: 'crossplane-system'
  #   config_dir: "aws-ssm"
  # - name: "aws-eks"
  #   namespace: 'crossplane-system'
  #   config_dir: "aws-eks"
