---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: oisis-cp-bucket-example
spec:
  providerConfigRef:
    name: default
  forProvider:
    acl: private
    locationConstraint: us-east-1
    versioningConfiguration:
      status: Enabled
