---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: oisis-cp-bucket-example
spec:
  providerConfigRef:
    name: aws-provider-config
  forProvider:
    locationConstraint: us-east-1
    versioningConfiguration:
      status: Enabled
    tagging:
      tagSet:
        - key: Owner
          value: CP-example