---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: cp-vpc
spec:
  providerConfigRef:
    name: default
  forProvider:
    cidrBlock: "10.0.0.0/16"
    enableDnsSupport: true
    enableDnsHostNames: true
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: cp-vpc-sn
spec:
  providerConfigRef:
    name: default
  forProvider:
    vpcIdRef:
      name: cp-vpc
    region: us-east-1
    cidrBlock: "10.0.1.0/24"
    availabilityZone: "us-east-1a"
    mapPublicIPOnLaunch: true
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  name: cp-vpc-igw
spec:
  providerConfigRef:
    name: default
  forProvider:
    vpcIdRef:
      name: cp-vpc
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: cp-vpc-rt
spec:
  providerConfigRef:
    name: default
  forProvider:
    associations:
      - subnetIdRef:
          name: cp-vpc-sn
    vpcIdRef:
      name: cp-vpc
    routes:
      - destinationCidrBlock: "0.0.0.0/0"
        gatewayIdRef:
          name: cp-vpc-igw
