---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-upbound-pc
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: "Retry=5;FailFast=true;SkipDryRunOnMissingResource=true,Validate=false"
spec:
  credentials:
    source: Secret
    secretRef:
      key: creds
      name: aws-secret
      namespace: crossplane-system