global:
  domain: localhost:8080
  additionalLabels:
    environment: dev
configs:
  cm:
    passwordPattern: "^.{4,32}$"
    url: 'http://localhost:8080/'
    statusbadge.url: 'http://localhost:8080/'
    accounts.root: apiKey, login
    accounts.root.enabled: true
    accounts.viewer: login
    accounts.viewer.enabled: true
    application.resourceTrackingMethod: annotation
    resource.customizations: |
      "*.upbound.io/*":
        health.lua: |
          health_status = {
            status = "Progressing",
            message = "Provisioning ..."
          }

          local function contains (table, val)
            for i, v in ipairs(table) do
              if v == val then
                return true
              end
            end
            return false
          end

          local has_no_status = {
            "ProviderConfig",
            "ProviderConfigUsage"
          }

          if obj.status == nil or next(obj.status) == nil and contains(has_no_status, obj.kind) then
            health_status.status = "Healthy"
            health_status.message = "Resource is up-to-date."
            return health_status
          end

          if obj.status == nil or next(obj.status) == nil or obj.status.conditions == nil then
            if obj.kind == "ProviderConfig" and obj.status.users ~= nil then
              health_status.status = "Healthy"
              health_status.message = "Resource is in use."
              return health_status
            end
            return health_status
          end

          for i, condition in ipairs(obj.status.conditions) do
            if condition.type == "LastAsyncOperation" then
              if condition.status == "False" then
                health_status.status = "Degraded"
                health_status.message = condition.message
                return health_status
              end
            end

            if condition.type == "Synced" then
              if condition.status == "False" then
                health_status.status = "Degraded"
                health_status.message = condition.message
                return health_status
              end
            end

            if condition.type == "Ready" then
              if condition.status == "True" then
                health_status.status = "Healthy"
                health_status.message = "Resource is up-to-date."
                return health_status
              end
            end
          end

          return health_status

      "*.crossplane.io/*":
        health.lua: |
          health_status = {
            status = "Progressing",
            message = "Provisioning ..."
          }

          local function contains (table, val)
            for i, v in ipairs(table) do
              if v == val then
                return true
              end
            end
            return false
          end

          local has_no_status = {
            "Composition",
            "CompositionRevision",
            "DeploymentRuntimeConfig",
            "ControllerConfig",
            "ProviderConfig",
            "ProviderConfigUsage"
          }
          if obj.status == nil or next(obj.status) == nil and contains(has_no_status, obj.kind) then
              health_status.status = "Healthy"
              health_status.message = "Resource is up-to-date."
            return health_status
          end

          if obj.status == nil or next(obj.status) == nil or obj.status.conditions == nil then
            if obj.kind == "ProviderConfig" and obj.status.users ~= nil then
              health_status.status = "Healthy"
              health_status.message = "Resource is in use."
              return health_status
            end
            return health_status
          end

          for i, condition in ipairs(obj.status.conditions) do
            if condition.type == "LastAsyncOperation" then
              if condition.status == "False" then
                health_status.status = "Degraded"
                health_status.message = condition.message
                return health_status
              end
            end

            if condition.type == "Synced" then
              if condition.status == "False" then
                health_status.status = "Degraded"
                health_status.message = condition.message
                return health_status
              end
            end

            if contains({"Ready", "Healthy", "Offered", "Established"}, condition.type) then
              if condition.status == "True" then
                health_status.status = "Healthy"
                health_status.message = "Resource is up-to-date."
                return health_status
              end
            end
          end

          return health_status
    resource.exclusions: |
      - apiGroups:
        - "*"
        kinds:
        - ProviderConfigUsage
  rbac:
    # RBAC doc: https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/
    # https://github.com/argoproj/argo-cd/blob/master/assets/builtin-policy.csv
    policy.csv: |
      p, role:viewer, applications, get, */*, allow
      p, role:viewer, applications, create, */*, deny
      p, role:viewer, applications, update, */*, deny
      p, role:viewer, applications, delete, */*, deny
      p, role:viewer, applications, sync, */*, allow
      p, role:viewer, applications, override, */*, allow
      p, role:viewer, applications, action/*, */*, allow
      p, role:viewer, applicationsets, get, */*, allow
      p, role:viewer, applicationsets, create, */*, deny
      p, role:viewer, applicationsets, update, */*, deny
      p, role:viewer, applicationsets, delete, */*, deny
      p, role:viewer, certificates, get, *, allow
      p, role:viewer, certificates, create, *, deny
      p, role:viewer, certificates, update, *, deny
      p, role:viewer, certificates, delete, *, deny
      p, role:viewer, clusters, get, *, allow
      p, role:viewer, clusters, create, *, deny
      p, role:viewer, clusters, update, *, deny
      p, role:viewer, clusters, delete, *, deny
      p, role:viewer, repositories, get, *, allow
      p, role:viewer, repositories, create, *, deny
      p, role:viewer, repositories, update, *, deny
      p, role:viewer, repositories, delete, *, deny
      p, role:viewer, write-repositories, get, *, deny
      p, role:viewer, write-repositories, create, *, deny
      p, role:viewer, write-repositories, update, *, deny
      p, role:viewer, write-repositories, delete, *, deny
      p, role:viewer, projects, get, *, allow
      p, role:viewer, projects, create, *, deny
      p, role:viewer, projects, update, *, deny
      p, role:viewer, projects, delete, *, deny
      p, role:viewer, accounts, get, *, deny
      p, role:viewer, gpgkeys, get, *, deny
      p, role:viewer, logs, get, */*, deny
      p, role:viewer, exec, create, */*, deny
      g, admin, role:admin
      g, root, role:admin
      g, viewer, role:viewer
    policy.default: role:readonly
  secret:
    extra:
      # HOWTO: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-secret.yaml
      # To generate password run command: htpasswd -nbBC 10 "" admin123 | tr -d ':\n' | sed 's/$2y/$2a/'
      # admin password: admin
      admin.password: $2a$10$WeVnTGLH/oq1XSuVIkGj6udjNQmizKhZyeuLKClTz.KLkvwaO.T0a
      # root password: root
      accounts.root.password: $2a$10$CnKwv3a19BhDTCHWUplCYOYSjH327ELWVUxzfQ.DABviVKaN4tXCC
      # viewer password: viewer
      accounts.viewer.password: $2a$10$xWt7ReCGnmITwTSFkQDs6eBt3derfSmVUCU16HUug7uChWkUgb9zu
controller:
  env:
  - name: ARGOCD_K8S_CLIENT_QPS
    value: "300"