---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-upbound-pc
spec:
  credentials:
    source: Secret
    secretRef:
      key: creds
      name: aws-secret
      namespace: crossplane-system
