---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: vpc-1-priv-us-east-1a-subnet
  # annotations:
  #   crossplane.io/external-name: subnet-08fabd0299c17c277 # manage existing Subnet
  labels:
    name: vpc-1-priv-us-east-1a-subnet
    kubernetes.io/role/internal-elb: "1"
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    availabilityZone: us-east-1a
    cidrBlock: 10.10.1.0/24
    region: us-east-1
    tags:
      Name: vpc-1-priv-us-east-1a-subnet
      ManagedBy: Crossplane
    vpcIdRef:
      name: vpc-1
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: vpc-1-priv-us-east-1b-subnet
  # annotations:
  #   crossplane.io/external-name: subnet-03c18525e77fda56b # manage existing Subnet
  labels:
    name: vpc-1-priv-us-east-1b-subnet
    kubernetes.io/role/internal-elb: "1"
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    availabilityZone: us-east-1b
    cidrBlock: 10.10.2.0/24
    region: us-east-1
    tags:
      Name: vpc-1-priv-us-east-1b-subnet
      ManagedBy: Crossplane
    vpcIdRef:
      name: vpc-1
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: vpc-1-pub-us-east-1a-subnet
  # annotations:
  #   crossplane.io/external-name: subnet-0d4def7ee346b5654 # manage existing Subnet
  labels:
    name: vpc-1-pub-us-east-1a-subnet
    kubernetes.io/role/elb: "1"
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    availabilityZone: us-east-1a
    cidrBlock: 10.10.3.0/24
    region: us-east-1
    tags:
      Name: vpc-1-pub-us-east-1a-subnet
      ManagedBy: Crossplane 
    vpcIdRef:
      name: vpc-1
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: vpc-1-pub-us-east-1b-subnet
  # annotations:
  #   crossplane.io/external-name: subnet-0cef0db5956f355f0 # manage existing Subnet
  labels:
    name: vpc-1-pub-us-east-1b-subnet
    kubernetes.io/role/elb: "1"
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    availabilityZone: us-east-1b
    cidrBlock: 10.10.4.0/24
    region: us-east-1
    tags:
      Name: vpc-1-pub-us-east-1b-subnet
      ManagedBy: Crossplane 
    vpcIdRef:
      name: vpc-1
