---
apiVersion: cloudwatchlogs.aws.upbound.io/v1beta1
kind: Group
metadata:
  name: /aws/vpc/vpc-1
  # annotations:
  #   crossplane.io/external-name: vpc-06b5984e75c31ff46 # manage existing VPC
  labels:
    name: aws_vpc_vpc-1
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    region: us-east-1
    retentionInDays: 7
    logGroupClass: STANDARD
    tags:
      ManagedBy: Crossplane
      Name: vpc-1
      VPC_Name: vpc-1
