---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: FlowLog
metadata:
  name: vpc-1-flowlog
  # annotations:
  #   crossplane.io/external-name: sg-0e880dcde534bafc1 # manage existing SecurityGroup
  labels:
    name: vpc-1-cludwatch-role
    ManagedBy: crossplane
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    iamRoleArnRef:
      name: vpc-1-cludwatch-role
    logDestinationSelector:
      name: aws.vpc.vpc-1
    region: us-east-1
    logDestinationType: cloud-watch-logs
    maxAggregationInterval: 600
    trafficType: ALL
    vpcIdRef:
      name: vpc-1
    tags:
      ManagedBy: Crossplane
      Name: vpc-1-flowlog
