---
apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: eks-1
  # annotations:
  #   crossplane.io/external-name: subnet-03c18525e77fda56b # manage existing Subnet
  labels:
    name: eks-1
    argocd.argoproj.io/instance: eks-1
spec:
  providerConfigRef:
    name: aws-upbound-pc
  # deletionPolicy: Orphan # Do not delete resource even you will delete it from crossplane
  forProvider:
    region: us-east-1
    accessConfig:
      - authenticationMode: API_AND_CONFIG_MAP
        bootstrapClusterCreatorAdminPermissions: false
    bootstrapSelfManagedAddons: false
    computeConfig:
      - enabled: true
        nodePools: 
          - general-purpose
        nodeRoleArn: eks-1-nodepool-role
    enabledClusterLogTypes:
      - api
      - audit
      - authenticator
      - controllerManager
      - scheduler
    kubernetesNetworkConfig:
      - elasticLoadBalancing:
          - enabled: true
        ipFamily: ipv4
        serviceIpv4Cidr: 172.20.0.0/16
    roleArnRef:
      name: eks-1-cluster-role
    storageConfig:
      - blockStorage:
        - enabled: true
    tags:
      Name: eks-1
      ManagedBy: crossplane
    upgradePolicy:
      - supportType: STANDARD
    version: "1.32"
    vpcConfig:
      - subnetIdRefs:
          - name: vpc-1-pub-us-east-1a-subnet
          - name: vpc-1-pub-us-east-1b-subnet
        endpointPrivateAccess: true
        endpointPublicAccess: true
        publicAccessCidrs: 
          - "0.0.0.0/0"