---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: aws-secret
data:
  creds: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQVEzRUdSR1I3V0xWNFdYNlQKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gNll5MFJQODVyOFhNMVd0eXZ1emxZOXYwNE0yRkRDdTIxSGZLekNPLwo=
