---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: aws-secret
data:
  creds: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQTRNVFdKR0hZR0ZKSU03Tk0KYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0ga3NCanBNTzFQdnRmb00vTVlYNitSeldwTEpxOWRSQ3NGZEZTZTRvKwo=
