customAnnotations:
  helm.sh/hook: crd-install
service:
  customAnnotations:
    helm.sh/hook: crd-install
# provider:
#   packages:
#     - "xpkg.upbound.io/upbound/provider-aws-s3:v1"
#     - "xpkg.upbound.io/upbound/provider-aws-ec2:v1"
#     - "xpkg.upbound.io/upbound/provider-aws-ssm:v1"
#     - "xpkg.upbound.io/upbound/provider-aws-iam:v1"
#     - "xpkg.upbound.io/upbound/provider-aws-eks:v1"
